# Introduction to NumPy

In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.33],[4.02,5,6]])
a3 = np.array([[[1.1,2.05,6.35],[2.3,6.35,5.21],[6,8,2]],[[10,11,12],[13,14,15],[16,17,18]]])

In [5]:
a2

array([[1.  , 2.  , 3.33],
       [4.02, 5.  , 6.  ]])

In [6]:
a3

array([[[ 1.1 ,  2.05,  6.35],
        [ 2.3 ,  6.35,  5.21],
        [ 6.  ,  8.  ,  2.  ]],

       [[10.  , 11.  , 12.  ],
        [13.  , 14.  , 15.  ],
        [16.  , 17.  , 18.  ]]])